### ISSUE TITLE
因115禁止第三方下载失效

### ISSUE THREAD

**Issue by jackiejtr** [gameclamp/115fullspeed#2]
http://pc.115.com/notice/index.html
http://115.com/115/T257368.html
能解决么大大

**Comment by gameclamp** [comment]
aria2c已修复，potplayer就不好办了，貌似无法自定义它网络请求的header

**Comment by jackiejtr** [comment]
十分感谢 我试试kodi那种115插件否直接用

**Comment by wxyzh** [comment]
@gameclamp 是否可以直接使用，115播放器的地址？
![115-mpv](https://cloud.githubusercontent.com/assets/19548073/24383887/77f3a588-1392-11e7-9b80-8d4a4e289042.png)

**Comment by gameclamp** [comment]
那就不是原画了吧，目标还是直接播放没压缩过的文件。

**Comment by jackiejtr** [comment]
kodi的115插件仍然可用http://www.hdpfans.com/thread-604090-1-1.html

**Comment by gameclamp** [comment]
现在发现下载单线程限速3.2MB/S……

**Comment by jackiejtr** [comment]
唉 比没有强。。

**Comment by wxyzh** [comment]
@gameclamp 115的网页版可以选择播放原话。
另外我用wget 下载并重定向像输出到mpv，是可以播放的，但是不能拖动进度条

**Comment by jackiejtr** [comment]
突然改版可以了

**Comment by gameclamp** [comment]
@wxyzh 那个原画也是压过的。
让播放软件直接请求的用意就是为了拖进度条。

**Comment by gameclamp** [comment]
@jackiejtr 改版之后又恢复了不检查cookies的设计了。不过忙时的限速还是3.2MB/S，白天就能满速。

**Comment by jackiejtr** [comment]
还算能接受。。

**Comment by jackiejtr** [comment]
新版界面稍微有些错位 大神有时间的话麻烦您费心了

**Comment by sk520kj** [comment]
大大能给个联系方式么！~~或者您加我一下QQ有急事找您，我用了您的这个脚本但是不载入aria2啊。感谢

**Comment by gameclamp** [comment]
@sk520kj aria2c部分简陋，只发送请求到127.0.0.1，无验证

**Comment by sk520kj** [comment]
请问下现在是不是用aria2c也被限速50KB了啊，老大能留一个联系方式么，或者您加我QQ吧2363979055，找您有急事啊，感谢

**Comment by gameclamp** [comment]
@sk520kj 速度只跟VIP、线路和是否繁忙时间有关，脚本和工具不能改变速度。
