### ISSUE TITLE
有一些后缀名为大写MP4的 无法使用

### ISSUE THREAD

**Issue by jackiejtr** [gameclamp/115fullspeed#4]
麻烦您了

**Comment by gameclamp** [comment]
并没有大写的扩展名啊，尝试在本地将扩展名改成了大写，传上去也自动变小写

**Comment by jackiejtr** [comment]
我可以开车么。。magnet:?xt=urn:btih:3595b93cb1d58e5236a36d649a4eef0e6a238422 这个链接里面的 
![image](https://cloud.githubusercontent.com/assets/14011172/26581567/34ac1c66-4578-11e7-9388-7642ad147be9.png)

**Comment by gameclamp** [comment]
并没有
![default](https://cloud.githubusercontent.com/assets/1432607/26629410/d93b74ea-4634-11e7-8881-e516e6ba6ea4.png)
