### ISSUE TITLE
导出 ASX 使用 https 而不是 http

### ISSUE THREAD

**Issue by zizhengwu** [gameclamp/115fullspeed#6]
打开了 ASX 文件里面似乎是

    Ref href ="http://vipcdnuni.115.com/..."

实测改为

    Ref href ="https://vipcdnuni.115.com/..."

也可以使用

**Comment by gameclamp** [comment]
这个地址是根据你115账号的高级设置，SSL加密下载开关来决定的。打开了SSL加密下载就会返回https地址。

**Comment by zizhengwu** [comment]
thx
